"use strict";
exports.__esModule = true;
var mockdate = require("./index");
mockdate.set(new Date());
mockdate.set('2017-01-05');
mockdate.set(new Date().getTime());
mockdate.set(new Date(), 0);
mockdate.reset();
mockdate.startTicking(100);
mockdate.startTicking();
mockdate.stopTickinsg();
